### ISSUE TITLE
Add support for --disable-sandboxing

### ISSUE THREAD

**Issue by zoickx** [vzaliva/coq-config#5]
Required to work within unprivileged Docker. See https://github.com/ocaml/opam/issues/4327.

**Comment by zoickx** [comment]
Note: this option is installation-wide, passed to `opam init` rather than `opam switch` subcommands.

**Comment by zoickx** [comment]
I do not believe e04be97 fixes this issue correctly. In fact, I'm pretty sure it is going break the tool.
As I noted, `--disable-sandboxing` is an option of the `opam init` subcommand, not `opam switch`:
``` shell
$ opam switch create test --no-switch --disable-sandboxing
opam: unknown option `--disable-sandboxing', did you mean `-d' ?
Usage: opam switch [OPTION]... [COMMAND] [ARG]...
Try `opam switch --help' or `opam --help' for more information.
```
This should only be implemented after the first TODO item of
> * Run `opam init` if necessary

**Comment by vzaliva** [comment]
right. need more work.

**Comment by vzaliva** [comment]
I've reverted changes. Right now I am not sure if anything could be done to fix this issue, as `opam init` is happening outside of this tool. If you have some ideas how this could be implemented, please elaborate.
